name: "Mix Dependency Submission"

on:
  push:
    branches:
      - "main"

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write

jobs:
  report_mix_deps:
    name: "Report Mix Dependencies"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: erlef/mix-dependency-submission@v1
        with:
          # Ignore the demo app's mix.exs so only the main project's dependencies are submitted
          ignore: priv/modkit_demo-master
